services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-notes
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  clickhouse-data:
