"""SQLAlchemy ORM demonstration using a self-contained SQLite database.

Install:
    python -m pip install sqlalchemy

Run:
    python scripts/orm/sqlalchemy_demo.py
"""

from __future__ import annotations

from sqlalchemy import ForeignKey, String, create_engine, select
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    Session,
    mapped_column,
    relationship,
    selectinload,
)


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)

    posts: Mapped[list["Post"]] = relationship(
        back_populates="author",
        cascade="all, delete-orphan",
    )


class Post(Base):
    __tablename__ = "posts"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False)
    title: Mapped[str] = mapped_column(String(200), nullable=False)

    author: Mapped[User] = relationship(back_populates="posts")


def main() -> None:
    # echo=True is deliberate: the demo lets you see the SQL generated by the ORM.
    engine = create_engine("sqlite:///:memory:", echo=True)
    Base.metadata.create_all(engine)

    with Session(engine) as session:
        with session.begin():
            alice = User(
                name="Alice",
                posts=[Post(title="ORM notes"), Post(title="Transactions")],
            )
            bob = User(
                name="Bob",
                posts=[Post(title="Indexes")],
            )
            session.add_all([alice, bob])

        # selectinload avoids one lazy-load query per user.
        statement = (
            select(User)
            .options(selectinload(User.posts))
            .order_by(User.id)
        )
        users = session.scalars(statement).all()

        print("\nUsers and posts:")
        for user in users:
            titles = ", ".join(post.title for post in user.posts)
            print(f"{user.name}: {titles}")

        with session.begin():
            alice = session.scalar(select(User).where(User.name == "Alice"))
            if alice is None:
                raise RuntimeError("Expected Alice to exist")
            alice.name = "Alicia"

        names = session.scalars(select(User.name).order_by(User.id)).all()
        print("\nNames after update:", names)


if __name__ == "__main__":
    main()
